# This is a boilerplate parameters config generated for pipeline 'MLP'
# using Kedro 0.17.6.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.17.6/04_kedro_project_setup/02_configuration.html#parameters

batch_size: 128
lr: 1e-3
weight_decay: 1e-5
epochs: 12